version: '3'

services:
  aiprivateinterface-service:
    build:
      context: .
      dockerfile: Dockerfile.aiprivateinterface
    ports:
      - "50057:50057"
    working_dir: /app
    command: python server.py
    # environment:
    #   - GRPC_VERBOSITY=debug

  aiprocessing-service:
    build:
      context: .
      dockerfile: Dockerfile.aiprocessing
    depends_on:
      - aiprivateinterface-service
    ports:
      - "50051:50051"
    working_dir: /app
    command: python server.py
    # environment:
    #   - GRPC_VERBOSITY=debug

  grpc-client:
    build:
      context: .
      dockerfile: Dockerfile.client  
    depends_on:
      - aiprocessing-service
    working_dir: /app
    command: python client.py
